### ISSUE TITLE
It is impossible to install the plugin

### ISSUE THREAD

**Issue by mak-42** [zaunerc/eclipserunnerplugin#6]
The plugin is hosted on bintray, which was terminated on the 1st of May 2021: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
It is impossible to install the plugin now :(

**Comment by zaunerc** [comment]
I am going to setup a new Eclipse P2 update site. The new update site should be online in the next two to three days.

**Comment by zaunerc** [comment]
The new update site is now located at https://erp.nllk.net/p2/com.eclipserunner.p2_site/latest/. The plugin info over at the Eclipse market place has already been updated. I still have to update some links in the source code repo though (the links to the bintray p2 repo in the README.md file).

Thanks @mak-42 for filling this issue.
