### ISSUE TITLE
Export settings

### ISSUE THREAD

**Issue by aperrad** [zaunerc/eclipserunnerplugin#9]
As a team lead, I would like to share a common base of run configuration. 

Export settings would be really helpful for that. 
I also think it would be useful to send you our configuration to reproduce bugs easily

**Comment by zaunerc** [comment]
Hi @aperrad. Sorry, but at the moment I have no time to work on any new features for this plugin. But you are more than welcome to contribute code which implements new features through a pull request. If you need help to get everything up and running to work on the eclipse-runner-plugin just let me know.
